name: Besiege Calmcode with Locust

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install Python dependencies 
      run: python -m pip install --upgrade pip; python -m pip install -r scripts/locust/requirements.txt
    - name: Fetch latest data
      run: locust -f scripts/locust/locu.py --headless --host http://calmcode.io -u 250 -r 50 --csv-full-history --csv locust --run-time 30s
    - name: Stack CSV Files
      run: python common.py stack locust_stats_history.csv datasets/locust_stats_history.csv
    - name: Remove Other Files
      run: rm -rf *.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
